### ISSUE TITLE
Update template for private model

### ISSUE THREAD

**Issue by zhuangqh** [kaito-project/headlamp-kaito#15]
```yaml
apiVersion: kaito.sh/v1beta1
kind: Workspace
metadata:
  name: workspace-llama-3.3-70b-instruct
resource:
  instanceType: Standard_NC96ads_A100_v4
  labelSelector:
    matchLabels:
      apps: llama-3.3-70b-instruct
inference:
  preset:
    name: llama-3.3-70b-instruct
```

For this kind of private model, users are required to provide a hf secret to download model.
It would be better to provide a placeholder here.  Ref https://github.com/kaito-project/kaito/blob/main/examples/inference/kaito_workspace_llama-3.3_70b_instruct.yaml

Otherwise, users are unable to create this workspace successfully.

expected to
```
apiVersion: kaito.sh/v1beta1
kind: Workspace
metadata:
  name: workspace-llama-3-3-70b-instruct
resource:
  count: 2
  instanceType: "Standard_NC48ads_A100_v4"
  labelSelector:
    matchLabels:
      apps: llama-3-3-70b-instruct
inference:
  config: "ds-inference-params"
  preset:
    name: llama-3.3-70b-instruct
    presetOptions:
      modelAccessSecret: hf-token
---
apiVersion: v1
kind: Secret
metadata:
  name: hf-token
type: Opaque
data:
  HF_TOKEN: # your secret here.
```
